/* eslint no-unused-vars: off */
/* eslint no-global-assign: off */
/* global systemDictionary */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
"use strict";

systemDictionary = {
	"prayer_time adapter settings": {
		"en": "Adapter settings for prayer_time",
		"de": "Adaptereinstellungen für prayer_time",
		"ru": "Настройки адаптера для prayer_time",
		"pt": "Configurações do adaptador para prayer_time",
		"nl": "Adapterinstellingen voor prayer_time",
		"fr": "Paramètres d'adaptateur pour prayer_time",
		"it": "Impostazioni dell'adattatore per prayer_time",
		"es": "Ajustes del adaptador para prayer_time",
		"pl": "Ustawienia adaptera dla prayer_time",
		"zh-cn": "prayer_time的适配器设置"
	},
	"Sabah": {
		"en": "Sabah",
		"de": "Sabah",
		"ru": "Sabah",
		"pt": "Sabah",
		"nl": "Sabah",
		"fr": "Sabah",
		"it": "Sabah",
		"es": "Sabah",
		"pl": "Sabah",
		"zh-cn": "Sabah"
	},
	"Ögle": {
		"en": "Ögle",
		"de": "Ögle",
		"ru": "Ögle",
		"pt": "Ögle",
		"nl": "Ögle",
		"fr": "Ögle",
		"it": "Ögle",
		"es": "Ögle",
		"pl": "Ögle",
		"zh-cn": "Ögle"
	},
	"ikindi": {
		"en": "ikindi",
		"de": "ikindi",
		"ru": "ikindi",
		"pt": "ikindi",
		"nl": "ikindi",
		"fr": "ikindi",
		"it": "ikindi",
		"es": "ikindi",
		"pl": "ikindi",
		"zh-cn": "ikindi"
	},
	"Aksam": {
		"en": "Aksam",
		"de": "Aksam",
		"ru": "Aksam",
		"pt": "Aksam",
		"nl": "Aksam",
		"fr": "Aksam",
		"it": "Aksam",
		"es": "Aksam",
		"pl": "Aksam",
		"zh-cn": "Aksam"
	},
	"Yatsi": {
		"en": "Yatsi",
		"de": "Yatsi",
		"ru": "Yatsi",
		"pt": "Yatsi",
		"nl": "Yatsi",
		"fr": "Yatsi",
		"it": "Yatsi",
		"es": "Yatsi",
		"pl": "Yatsi",
		"zh-cn": "Yatsi"
	}
};